command_prefix: "#"
servers:
    1.16.2 flat:
        # rootFolder: G:\_MC\_Server\_AzurCraft\1.16.2 flat
        execOptions: -Xms4G -Xmx4G
        execPath: G:\_MC\_Server\_AzurCraft\1.16.2 flat\server.jar
        # scriptFile: 1.16.2 flat.bat
    # 1.16.2-sit creative:
    #     rootFolder: G:\_MC\_Server\_AzurCraft\1.16.2-sit creative
    #     scriptFile: 1.16.2-sit creative.bat
    # 1.16.2-sit survival:
    #     rootFolder: G:\_MC\_Server\_AzurCraft\1.16.2-sit survival
    #     scriptFile: 1.16.2-sit survival.bat